name: Split Deploy (Frontend to Pages, Backend to VPS)

on:
  push:
    branches:
      - main # Если ветка называется master, замени на master

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  deploy-front:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Pages
        uses: actions/configure-pages@v5

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: './frontend'

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4

  deploy-back:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      # Копируем папку бэка и файл продакшен-композа на твой VPS-сервер
      - name: Copy Backend & Compose to VPS
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.SERVER_HOST }}     # IP сервера (из Secrets)
          username: root
          key: ${{ secrets.SSH_PRIVATE_KEY }}   # Твой приватный SSH-ключ (из Secrets)
          source: "./backend,./docker-compose.prod.yml"
          target: "/var/www/my_project"

      # Подключаемся к серверу по SSH и запускаем Docker Compose
      - name: SSH Build and Restart Backend
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: root
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            cd /var/www/my_project
            
            # Переносим секреты из гитхаба в реальный файл .env на сервере
            echo "${{ secrets.ENV_FILE }}" > ./backend/.env
            
            # Поднимаем продакшен контейнер с Gunicorn и 4 воркерами одной командой!
            docker compose -f docker-compose.prod.yml up --build -d